#theme: jekyll-theme-minimal

theme: just-the-docs
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/", "firmware/"]
title: "CNC base 3-axis remotely controlled pick and place robot"

back_to_top: true
back_to_top_text: "Back to top"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-2709176-10
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# plugins:
#  - jekyll-seo-tag
